### ISSUE TITLE
Error in annotate_nominatum.py

### ISSUE THREAD

**Issue by simonw** [simonw/museums#41]
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "annotate_nominatum.py", line 27, in <module>
    annotate(db)
  File "annotate_nominatum.py", line 14, in annotate
    data = requests.get(API_URL.format(row["latitude"], row["longitude"])).json()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simonw** [comment]
I'm going to disable it for the moment.
